const genre = [
    "3d",
    "ahegao",
    "anal",
    "bdsm",
    "big boobs",
    "blow job",
    "bondage",
    "boob job",
    "censored",
    "comedy",
    "cosplay",
    "creampie",
    "dark skin",
    "facial",
    "fantasy",
    "filmed",
    "foot job",
    "futanari",
    "gangbang",
    "glasses",
    "hand job",
    "harem",
    "hd",
    "horror",
    "incest",
    "inflation",
    "lactation",
    "loli",
    "maid",
    "masturbation",
    "milf",
    "mind break",
    "mind control",
    "monster",
    "nekomimi",
    "ntr",
    "nurse",
    "orgy",
    "plot",
    "pov",
    "pregnant",
    "public sex",
    "rape",
    "reverse rape",
    "rimjob",
    "scat",
    "school girl",
    "shota",
    "softcore",
    "swimsuit",
    "teacher",
    "tentacle",
    "threesome",
    "toys",
    "trap",
    "tsundere",
    "ugly bastard",
    "uncensored",
    "vanilla",
    "virgin",
    "watersports",
    "x-ray",
    "yaoi",
    "yuri",
  ];
  
  const logo = "https://i.imgur.com/sZ7Fmbl.png";

  const catalogCategories = {
    Newset : "newset",
    Mostlikes: "mostlikes",
    MostViews: "mostviews",
    Recent: "recent",
  }

  const catalogExtrass = [
    {
      name: "search",
      isRequired: false,
    },
    {
      name: "skip",
      isRequired: false,
    },
    {
      name: "genre",
      options: genre,
      isRequired: false,
    },
  ];

  module.exports.genre = genre;
  module.exports.logo = logo;
  module.exports.catalogCategories = catalogCategories;
  module.exports.catalogExtrass = catalogExtrass;